SET TERM ^ ;
CREATE PROCEDURE GENERATE_UNIQUE_ID
RETURNS (
    RET Varchar(8000) )
AS
DECLARE VARIABLE SECT VARCHAR(50);
DECLARE VARIABLE RAND_NUM BIGINT;
DECLARE VARIABLE TMP BIGINT;
BEGIN
  ret = '';
  EXECUTE PROCEDURE RAND returning_values RAND_NUM;
  EXECUTE PROCEDURE CONVERT_BIGINT_CHARSTRING(RAND_NUM) returning_values SECT;
  ret = SUBSTRING(SECT FROM 4 FOR 4) ||'-';
  TMP = RAND_NUM;
  EXECUTE PROCEDURE RAND returning_values RAND_NUM;
  RAND_NUM = TMP + (RAND_NUM/2);
  TMP = RAND_NUM;
  EXECUTE PROCEDURE CONVERT_BIGINT_CHARSTRING(RAND_NUM) returning_values SECT;
  ret = ret||SUBSTRING(SECT FROM 1 FOR 8) ||'-';
  EXECUTE PROCEDURE RAND returning_values RAND_NUM;
  RAND_NUM = TMP - (RAND_NUM/4);
  TMP = RAND_NUM;
  EXECUTE PROCEDURE CONVERT_BIGINT_CHARSTRING(RAND_NUM) returning_values SECT;
  ret = ret||SUBSTRING(SECT FROM 1 FOR 8) ||'-';
  EXECUTE PROCEDURE RAND returning_values RAND_NUM;
  RAND_NUM = TMP + (RAND_NUM/6);
  TMP = RAND_NUM;
  EXECUTE PROCEDURE CONVERT_BIGINT_CHARSTRING(RAND_NUM) returning_values SECT;
  ret = ret||SUBSTRING(SECT FROM 1 FOR 8) ||'-';
  EXECUTE PROCEDURE RAND returning_values RAND_NUM;
  RAND_NUM = TMP - (RAND_NUM/8);
  TMP = RAND_NUM;
  EXECUTE PROCEDURE CONVERT_BIGINT_CHARSTRING(RAND_NUM) returning_values SECT;
  ret = ret||SUBSTRING(SECT FROM 4 FOR 4)||'.';
END^
SET TERM ; ^
